platform:ios, '8.0'
use_frameworks!

target 'HackathonClient' do
pod "Qiniu", :git => 'https://github.com/qiniu/objc-sdk.git', :branch => 'AFNetworking-3.x'
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage'
pod 'Mantle'
pod 'Masonry'
pod 'SVProgressHUD'
pod 'CYLTabBarController'
pod 'MJRefresh'
pod 'XHSetting'
pod 'TZImagePickerController', '~> 1.5.0'

#pod 'Qiniu'
end
